# Generated by Django 5.2.17 on 2026-08-20 13:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapaEspacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Capa')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('formato', models.CharField(choices=[('SHP', 'Shapefile (.zip)'), ('GPKG', 'GeoPackage (.gpkg)'), ('GEOJSON', 'GeoJSON / JSON'), ('KML', 'KML / KMZ'), ('GPX', 'GPX'), ('GML', 'GML'), ('GEOTIFF', 'GeoTIFF (.tif / .tiff)'), ('WFS', 'Servicio WFS (URL)')], max_length=10, verbose_name='Formato de Origen')),
                ('tipo_geometria', models.CharField(choices=[('POINT', 'Punto / MultiPunto'), ('LINESTRING', 'Línea / MultiLínea'), ('POLYGON', 'Polígono / MultiPolígono'), ('RASTER', 'Ráster / Malla'), ('UNKNOWN', 'Desconocido / WFS')], default='UNKNOWN', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='capas_espaciales/', verbose_name='Archivo Espacial')),
                ('url_wfs', models.URLField(blank=True, null=True, verbose_name='URL del Servicio WFS')),
                ('capa_wfs_layer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la capa WFS')),
                ('srid_origen', models.IntegerField(default=4326, verbose_name='SRID / EPSG Origen')),
                ('num_registros', models.IntegerField(default=0, verbose_name='Número de Objetos/Pixeles')),
                ('procesado_exitoso', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capa Espacial',
                'verbose_name_plural': 'Capas Espaciales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ElementoVectorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometría PostGIS')),
                ('atributos', models.JSONField(blank=True, default=dict, verbose_name='Atributos de la Entidad (Tabla de Atributos)')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='app_capas.capaespacial')),
            ],
            options={
                'indexes': [models.Index(fields=['capa'], name='app_capas_e_capa_id_c13e37_idx')],
            },
        ),
    ]
