# Generated by Django 5.2.17 on 2026-08-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visor_grafico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUltimoMes',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actividad_ultimo_mes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatNivelEducativo',
            fields=[
                ('id_nivel_educativo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cat_nivel_educativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CombustibleParaCocinar',
            fields=[
                ('id_combustible', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_combustible', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'combustible_para_cocinar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id_corte', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_corte', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoVida',
            fields=[
                ('id_curso_vida', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso_vida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'eps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FuenteObtencionAgua',
            fields=[
                ('id_fuente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_fuente', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fuente_obtencion_agua',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialVivienda',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'material_vivienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('pais_origen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramaSocial',
            fields=[
                ('id_programa_social', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'programa_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id_regimen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_regimen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'regimen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id_tipo_vivienda', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_vivienda', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_vivienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TratamientoAguaConsumo',
            fields=[
                ('id_tratamiento_agua', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tratamiento_agua_consumo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfiliacionSeguridadSocial',
            fields=[
                ('id_afiliacion', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.PROTECT, to='visor_grafico.municipios', to_field='mpio_cdpmp')),
                ('curso_vida', models.ForeignKey(blank=True, db_column='curso_vida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.cursovida')),
                ('eps', models.ForeignKey(blank=True, db_column='eps', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.eps')),
                ('nacionalidad', models.ForeignKey(blank=True, db_column='nacionalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.nacionalidad')),
                ('regimen', models.ForeignKey(blank=True, db_column='regimen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.regimen')),
                ('sexo', models.ForeignKey(blank=True, db_column='sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.sexo')),
            ],
            options={
                'db_table': 'afiliacion_seguridad_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EtapaVidaMadre',
            fields=[
                ('id_etapa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('curso_vida', models.ForeignKey(blank=True, db_column='curso_vida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.cursovida')),
            ],
            options={
                'db_table': 'etapa_vida_madre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JefeHogar',
            fields=[
                ('id', models.AutoField(db_column='id_jefe_hogar', primary_key=True, serialize=False)),
                ('desempleo_larga_duracion', models.BooleanField(blank=True, null=True)),
                ('trabajo_informal', models.BooleanField(blank=True, null=True)),
                ('grupo_sisben', models.CharField(blank=True, null=True)),
                ('nivel_sisben', models.IntegerField(blank=True, null=True)),
                ('llave', models.CharField(blank=True, null=True)),
                ('hogar', models.CharField(blank=True, null=True)),
                ('orden', models.CharField(blank=True, null=True)),
                ('actividad', models.ForeignKey(blank=True, db_column='actividad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.actividadultimomes')),
                ('corte', models.ForeignKey(blank=True, db_column='corte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.corte')),
                ('nivel_educativo', models.ForeignKey(blank=True, db_column='nivel_educativo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.catniveleducativo')),
                ('id_sexo', models.ForeignKey(blank=True, db_column='id_sexo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.sexo')),
            ],
            options={
                'db_table': 'jefe_hogar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MortalidadDesnutricion',
            fields=[
                ('id_mortalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.PROTECT, to='visor_grafico.municipios', to_field='mpio_cdpmp')),
                ('nacionalidad', models.ForeignKey(blank=True, db_column='nacionalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.nacionalidad')),
            ],
            options={
                'db_table': 'mortalidad_desnutricion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MortalidadInfantilPorEdad',
            fields=[
                ('id_mortalidad_edad', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('defunciones', models.IntegerField(blank=True, null=True)),
                ('mortalidad', models.ForeignKey(blank=True, db_column='mortalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.mortalidaddesnutricion')),
            ],
            options={
                'db_table': 'mortalidad_infantil_por_edad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DesnutricionAguda',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.PROTECT, to='visor_grafico.municipios', to_field='mpio_cdpmp')),
                ('nacionalidad', models.ForeignKey(blank=True, db_column='nacionalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.nacionalidad')),
            ],
            options={
                'db_table': 'desnutricion_aguda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BajoPesoNacer',
            fields=[
                ('id_registro_peso', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.PROTECT, to='visor_grafico.municipios', to_field='mpio_cdpmp')),
                ('etapa_vida_madre', models.ForeignKey(blank=True, db_column='etapa_vida_madre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.etapavidamadre')),
                ('nacionalidad', models.ForeignKey(blank=True, db_column='nacionalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.nacionalidad')),
            ],
            options={
                'db_table': 'bajo_peso_nacer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BajoPesoRegimen',
            fields=[
                ('id_bajo_peso_regimen', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_afectados', models.IntegerField(blank=True, null=True)),
                ('regimen', models.ForeignKey(blank=True, db_column='regimen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.regimen')),
            ],
            options={
                'db_table': 'bajo_peso_regimen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(db_column='id_vivienda', primary_key=True, serialize=False)),
                ('alcantarillado', models.BooleanField(blank=True, null=True)),
                ('acueducto', models.BooleanField(blank=True, null=True)),
                ('llave', models.CharField(blank=True, db_column='llave', null=True)),
                ('corte', models.ForeignKey(blank=True, db_column='corte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.corte')),
                ('material_vivienda', models.ForeignKey(blank=True, db_column='material_vivienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.materialvivienda')),
            ],
            options={
                'db_table': 'vivienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id_zona_geografica', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(blank=True, max_length=255, null=True)),
                ('casos_inseguridad_alimentaria', models.IntegerField(blank=True, null=True)),
                ('fex', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.DO_NOTHING, to='visor_grafico.municipios', to_field='mpio_cdpmp')),
            ],
            options={
                'db_table': 'zona_geografica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramaSocialZonaGeografica',
            fields=[
                ('pk', models.CompositePrimaryKey('id_zona', 'id_programa', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.programasocial')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.zonageografica')),
            ],
            options={
                'db_table': 'programa_social_zona_geografica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.AutoField(db_column='id_hogar', primary_key=True, serialize=False)),
                ('agua_llega_7_dias', models.BooleanField(blank=True, null=True)),
                ('cocina', models.BooleanField(blank=True, null=True)),
                ('nevera', models.BooleanField(blank=True, null=True)),
                ('total_personas_hogar', models.IntegerField(blank=True, null=True)),
                ('llave', models.CharField(blank=True, null=True)),
                ('hogar', models.CharField(blank=True, null=True)),
                ('cantidad_ninos', models.IntegerField(blank=True, null=True)),
                ('cantidad_adultos_mayores', models.IntegerField(blank=True, null=True)),
                ('afiliacion_seguridad_social', models.ForeignKey(blank=True, db_column='afiliacion_seguridad_social', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.afiliacionseguridadsocial')),
                ('combustible_para_cocinar', models.ForeignKey(blank=True, db_column='combustible_para_cocinar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.combustibleparacocinar')),
                ('corte', models.ForeignKey(blank=True, db_column='corte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.corte')),
                ('fuente_agua', models.ForeignKey(blank=True, db_column='fuente_agua', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.fuenteobtencionagua')),
                ('jefe_hogar', models.ForeignKey(blank=True, db_column='jefe_hogar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hogares_asociados', to='indicador_territorial.jefehogar')),
                ('tipo_vivienda', models.ForeignKey(blank=True, db_column='tipo_vivienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.tipovivienda')),
                ('tratamiento_agua', models.ForeignKey(blank=True, db_column='tratamiento_agua', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.tratamientoaguaconsumo')),
                ('vivienda', models.ForeignKey(blank=True, db_column='vivienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.vivienda')),
                ('zona_geografica', models.ForeignKey(blank=True, db_column='zona_geografica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indicador_territorial.zonageografica')),
            ],
            options={
                'db_table': 'hogar',
                'managed': True,
            },
        ),
    ]
