# Generated by Django 6.0.7 on 2026-07-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUltimoMes',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actividad_ultimo_mes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfiliacionSeguridadSocial',
            fields=[
                ('id_afiliacion', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'afiliacion_seguridad_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BajoPesoNacer',
            fields=[
                ('id_registro_peso', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bajo_peso_nacer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BajoPesoRegimen',
            fields=[
                ('id_bajo_peso_regimen', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_afectados', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bajo_peso_regimen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatNivelEducativo',
            fields=[
                ('id_nivel_educativo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cat_nivel_educativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CombustibleParaCocinar',
            fields=[
                ('id_combustible', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_combustible', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'combustible_para_cocinar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoVida',
            fields=[
                ('id_curso_vida', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso_vida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesnutricionAguda',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'desnutricion_aguda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtapaVidaMadre',
            fields=[
                ('id_etapa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'etapa_vida_madre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuenteObtencionAgua',
            fields=[
                ('id_fuente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_fuente', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fuente_obtencion_agua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id_hogar', models.IntegerField(primary_key=True, serialize=False)),
                ('estrato_socioeconomico', models.IntegerField(blank=True, null=True)),
                ('agua_llega_7_dias', models.BooleanField(blank=True, null=True)),
                ('cocina', models.BooleanField(blank=True, null=True)),
                ('nevera', models.BooleanField(blank=True, null=True)),
                ('alcantarillado', models.BooleanField(blank=True, null=True)),
                ('acueducto', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hogar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JefeHogar',
            fields=[
                ('id_jefe_hogar', models.IntegerField(primary_key=True, serialize=False)),
                ('ingreso_mensual', models.FloatField(blank=True, null=True)),
                ('desempleo_larga_duracion', models.BooleanField(blank=True, null=True)),
                ('trabajo_informal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jefe_hogar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialVivienda',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'material_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MortalidadDesnutricion',
            fields=[
                ('id_mortalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mortalidad_desnutricion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MortalidadInfantilPorEdad',
            fields=[
                ('id_mortalidad_edad', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('defunciones', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mortalidad_infantil_por_edad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('pais_origen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaSocial',
            fields=[
                ('id_programa_social', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'programa_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaSocialZonaGeografica',
            fields=[
                ('pk', models.CompositePrimaryKey('id_zona', 'id_programa', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'programa_social_zona_geografica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id_regimen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_regimen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'regimen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientoAguaConsumo',
            fields=[
                ('id_tratamiento_agua', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tratamiento_agua_consumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id_zona_geografica', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(blank=True, max_length=255, null=True)),
                ('casos_inseguridad_alimentaria', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zona_geografica',
                'managed': False,
            },
        ),
    ]
