# Generated by Django 6.0.7 on 2026-08-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador_territorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id_corte', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_corte', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id_tipo_vivienda', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_vivienda', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.IntegerField(primary_key=True, serialize=False)),
                ('alcantarillado', models.BooleanField(blank=True, null=True)),
                ('acueducto', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vivienda',
                'managed': False,
            },
        ),
    ]
