# Generated by Django 6.0.7 on 2026-07-28 02:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('dpto_ccdgo', models.CharField(max_length=5, unique=True, verbose_name='Código DANE Depto')),
                ('dpto_cnmbr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Depto')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=900914)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('mpio_cdpmp', models.CharField(max_length=5, unique=True, verbose_name='Código DANE Municipio')),
                ('dpto_cnmbr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Municipio')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=900914)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'managed': False,
            },
        ),
    ]
