# Generated by Django 5.2.17 on 2026-08-19 17:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('dpto_ccdgo', models.CharField(max_length=5, unique=True, verbose_name='Código DANE Depto')),
                ('dpto_cnmbr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Depto')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=9377)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('mpio_cdpmp', models.CharField(max_length=5, unique=True, verbose_name='Código DANE Municipio')),
                ('mpio_cnmbr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Municipio')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=9377)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veredas',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=900914)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('objectid', models.CharField(blank=True, null=True)),
                ('dptompio', models.CharField(blank=True, null=True)),
                ('codigo_ver', models.CharField(blank=True, null=True)),
                ('nom_dep', models.CharField(blank=True, null=True)),
                ('nomb_mpio', models.CharField(blank=True, null=True)),
                ('nombre_ver', models.CharField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, null=True)),
                ('descripcio', models.CharField(blank=True, null=True)),
                ('seudonimos', models.CharField(blank=True, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('cod_dpto', models.CharField(blank=True, null=True)),
                ('observacio', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veredas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vias',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('oneway', models.CharField(blank=True, max_length=1, null=True)),
                ('maxspeed', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('layer', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'public"."vias',
                'managed': False,
            },
        ),
    ]
