# Generated by Django 6.0.7 on 2026-07-28 04:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor_grafico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vias',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('oneway', models.CharField(blank=True, max_length=1, null=True)),
                ('maxspeed', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('layer', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='municipios',
            table='vias',
        ),
    ]
