# Generated by Django 5.2.17 on 2026-08-26 22:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor_grafico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaUrbana',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=900914)),
                ('dpto_ccdgo', models.CharField(blank=True, null=True)),
                ('mpio_ccdgo', models.CharField(blank=True, null=True)),
                ('mpio_cdpmp', models.CharField(blank=True, null=True)),
                ('clas_ccdgo', models.CharField(blank=True, null=True)),
                ('setr_ccdgo', models.CharField(blank=True, null=True)),
                ('setr_ccnct', models.CharField(blank=True, null=True)),
                ('secr_ccdgo', models.CharField(blank=True, null=True)),
                ('secr_ccnct', models.CharField(blank=True, null=True)),
                ('zu_ccdgo', models.CharField(blank=True, null=True)),
                ('zu_cdivi', models.CharField(blank=True, null=True)),
                ('zu_cnmbre', models.CharField(blank=True, null=True)),
                ('zu_ccnct', models.CharField(blank=True, null=True)),
                ('zu_narea', models.FloatField(blank=True, null=True)),
                ('zu_naltd', models.FloatField(blank=True, null=True)),
                ('zu_nano', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zona_urbana',
                'managed': False,
            },
        ),
    ]
