# Generated by Django 6.0.7 on 2026-07-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visor_grafico', '0002_vias_alter_municipios_options_alter_municipios_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipios',
            options={'managed': False, 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelTable(
            name='municipios',
            table='municipios',
        ),
    ]
