# Generated by Django 6.0.7 on 2026-08-04 02:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor_grafico', '0003_alter_municipios_options_alter_municipios_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veredas',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=900914)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('objectid', models.CharField(blank=True, null=True)),
                ('dptompio', models.CharField(blank=True, null=True)),
                ('codigo_ver', models.CharField(blank=True, null=True)),
                ('nom_dep', models.CharField(blank=True, null=True)),
                ('nomb_mpio', models.CharField(blank=True, null=True)),
                ('nombre_ver', models.CharField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, null=True)),
                ('descripcio', models.CharField(blank=True, null=True)),
                ('seudonimos', models.CharField(blank=True, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('cod_dpto', models.CharField(blank=True, null=True)),
                ('observacio', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veredas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vias',
            options={'managed': False},
        ),
    ]
