# Generated by Django 6.0.7 on 2026-08-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visor_grafico', '0004_veredas_alter_vias_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vias',
            table='public"."vias',
        ),
    ]
