# Generated by Django 6.0.7 on 2026-07-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesUsuario',
            fields=[
                ('id_rol_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'roles_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('entidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
