# Generated by Django 5.2.17 on 2026-08-26 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ingresarse en formato: '+573001234567'. De 7 a 15 dígitos.", regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono de Contacto'),
        ),
    ]
